apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  labels:
    k8s-app: java-maven-app
spec:
  selector:
    matchLabels:
      k8s-app: java-maven-app
  template:
    metadata:
      labels:
        k8s-app: java-maven-app
    spec:
      containers:
      - name: example-app
        image: {{ IMAGE }}
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 50m
            memory: 200Mi
        command: [ 'sh','-c','java -Xmx128m -jar /opt/*.jar && tail -f /var/log/lastlog' ]
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: example-app
  labels:
    k8s-app: java-maven-app
spec:
  selector:
    k8s-app: java-maven-app
  ports:
  - port: 8080
  type: NodePort
